config/routes.rb
Rails.application.routes.draw do
	resources :logins , :projects, :employees, :clients, :technologies
	post 'sessions/create'
  get 'sessions/destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :projects
	LIST=Client.all.collect {|c| [ c.name, c.id ]}

	validates :name, :country, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :technology
	LIST=Employee.all.collect {|e| [ e.name, e.id ]}
	def tech(em)
		@data = Employee.find_by("name=?", em)
		Technology.find_by("id=?", @data.technology).name
	end	
	
	def self.providePM
		Employee.where("role=?", "Project Manager").collect {|e| [e.name,e.id]}
	end
	validates :name,:email,:role,:experience,:technology_id, presence: true
	validates :status, inclusion: { in: [ true, false ] }
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "Enter Valid Email" }
	validates :experience, numericality: true
 	
end

app/models/login.rb
class Login < ApplicationRecord
	def self.ProvideType(t)
		Login.find(t).logintype
	end
end

app/models/project.rb
class DateValidator < ActiveModel::EachValidator
  def validate_each(project,start_date,value)
    unless value >= Date.today
    project.errors[start_date] << (options[:message] || "is invalid, please enter coming Date")
    end
  end
end

class Project < ApplicationRecord
  serialize :employee, Array
  belongs_to :client
  belongs_to :technology

  def projectPM(em)
		@data = Employee.find(em)
	end	
	def projectEMP(em)
		em.to_a
		@data = []
		0..len(em).each do |i|
			@data.push Employee.find(i).name
		end
		@data.name
	end	
	validates :name,:start_date,:end_date,:pm,:budget,:client_id,:technology_id,:employee, presence: true
	validates :budget, numericality: true
	validates :start_date, date: true
	validates :end_date, date: true
end

app/models/technology.rb
class Technology < ApplicationRecord
	has_many :employees
	has_many :projects
	LIST=Technology.all.collect {|c| [ c.name, c.id ]}
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	private   
    def current_user  
      Login.where(id: session[:checkuser_id] ).first   
    end   
    helper_method :current_user 
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	def index
	 	if session[:checkuser_id]
	        @client = Client.all
	  else 
	        flash[:success]="please Login First"
	        redirect_to logins_path
	  end
	end
	def new
		@client = Client.new
	end
	def edit
		@client = Client.find(params[:id])
	end
	def create
		@client = Client.new(client_params)
	 	if @client.save
			redirect_to clients_path
		else
			render 'new'
		end
	end
	def update
		@client = Client.find(params[:id])
		if @client.update(client_params)
			redirect_to clients_path
		else
			render 'edit'
		end
	end
	def destroy
  		@client = Client.find(params[:id])
  		@client.destroy
			redirect_to clients_path
	end
	private
		def client_params
			params.require(:client).permit(:name,:country)
		end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
def index
	 	if session[:checkuser_id]
	        @employee = Employee.all
	  else 
	        flash[:success]="please Login First"
	        redirect_to logins_path
	  end
	end
	def new
		@employee = Employee.new
	end
	def edit
		@employee = Employee.find(params[:id])
	end
	def create
		@employee = Employee.new(employee_params)
	 	if @employee.save
			redirect_to employees_path
		else
			render 'new'
		end
	end
	def update
		@employee = Employee.find(params[:id])
		if @employee.update(employee_params)
			redirect_to employees_path
		else
			render 'edit'
		end
	end
	def destroy
  		@employee = Employee.find(params[:id])
  		@employee.destroy
			redirect_to employees_path
	end
	private
		def employee_params
			param = params.require(:employee).permit(:name,:email,:role,:experience,:status,:technology_id)
		end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
	def new
		@login = Login.new
	end
	def index
		@login = Login.new
	end

	def create
		@login = Login.new(params.require(:login).permit(:logintype, :username, :password))
		if @login.save
			flash[:success]="Registered Successfully"
			redirect_to new_login_path
		else
			flash[:warning]="Error has Occured!! try again"
			render new_login_path
		end
	end
	def destroy
	  	session[:checkuser_id] = nil
	  	redirect_to logins_path
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
def index
	 	if session[:checkuser_id]
	        if params[:qry]
	        	@project = Project.where(pm: params[:qry])
	        else
	        	@project = Project.all
	        end
	  else 
	        flash[:success]="please Login First"
	        redirect_to logins_path
	  end
	end
	def new
		@project = Project.new
	end
	def edit
		@project = Project.find(params[:id])
	end
	def create
		@project = Project.new(project_params)
	 	if @project.save
			redirect_to projects_path
		else
			render 'new'
		end
	end
	def update
		@project = Project.find(params[:id])
		if @project.update(project_params)
			redirect_to projects_path
		else
			render 'edit'
		end
	end
	def destroy
  		@project = Project.find(params[:id])
  		@project.destroy
			redirect_to projects_path
	end
	private
		def project_params
			param = params.require(:project).permit(:name,:start_date,:end_date,:pm,:budget,:client_id,:technology_id,employee:[])
			# param[:client_id] = Client.find(param[:client_id])
			# param[:technology_id] = Technology.find(param[:technology_id])
			# param
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		@login = Login.new(params.require(:login).permit(:logintype, :username, :password))
		 	if Login.exists?(:username => @login.username)
        @checkuser = Login.where("username=?", @login.username)
        if @checkuser[0].password == @login.password && @checkuser[0].logintype == @login.logintype
        		session[:checkuser_id] = @checkuser[0].id
            flash[:success]="Successfully logged in!!!!!"
            redirect_to projects_path(@checkuser[0])
        else
            flash[:warning]="Enter correct Details"
            redirect_to logins_path
        end
		  else 
		        flash[:warning]="Enter correct username"
		        redirect_to logins_path
		  end
	end
	def destroy
	  	session[:checkuser_id] = nil
	  	redirect_to logins_path
	end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
	def index
	 	if session[:checkuser_id]
	        @technology = Technology.all
	  else 
	        flash[:success]="please Login First"
	        redirect_to logins_path
	  end
	end
	def new
		@technology = Technology.new
	end
	def edit
		@technology = Technology.find(params[:id])
	end
	def create
		@technology = Technology.new(technology_params)
	 	if @technology.save
			redirect_to technologies_path
		else
			render 'new'
		end
	end
	def update
		@technology = Technology.find(params[:id])
		if @technology.update(technology_params)
			redirect_to technologies_path
		else
			render 'edit'
		end
	end
	def destroy
  		@technology = Technology.find(params[:id])
  		@technology.destroy
			redirect_to technologies_path
	end
	private
		def technology_params
			params.require(:technology).permit(:name)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/clients/_form.html.erb
<div class="container">
  <h1>Add New Client</h1>
    <div class="jumbotron">
      <%= form_with scope: :client, url: clients_path  ,local: true do |form| %>
        <% if @client.errors.any? %>
          <div id="error_explanation">
            <ul>
              <% @client.errors.full_messages.each do |msg| %>
                <li style="color:gray;"><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= form.text_field :name , placeholder:'Enter Client Name',class:"form-control",required: true %>
        </div>
        <div class="form-group">
           <%= form.text_field :country , placeholder:'Enter Country', class:"form-control",required:true %>
        </div>
        <%= form.submit 'Submit' ,class:"btn btn-primary btn-md"%>
       <%= link_to 'Back', clients_path, class:"btn btn-primary btn-md"%>
      <% end %>
    </div>
</div>

app/views/clients/edit.html.erb
<div class="container">
  <h1>Add New Client</h1>
    <div class="jumbotron">
      <%= form_with scope: :client,url: client_path,method: :put,local: true do |form| %>
        <% if @client.errors.any? %>
          <div id="error_explanation">
            <ul>
              <% @client.errors.full_messages.each do |msg| %>
                <li style="color:gray;"><%= msg %></li>
                <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= form.text_field :name , placeholder:'Enter Client name',class:"form-control", required: true %>
        </div>
        <div class="form-group">
           <%= form.text_field :country , placeholder:'Enter Country Name', class:"form-control", required: true  %>
        </div>
        <%= form.submit 'Submit' ,class:"btn btn-primary btn-md"%>
       
      <% end %>
      
    </div>
</div>

app/views/clients/index.html.erb
<div class="container">
  <h1  style="font-family:arial">Listing All Clients</h1>
  <div class="jumbotron">
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <th>Country</th>
        <th></th>
        <th></th>
      </tr>
     <% @client.each do |client| %>
      <tr>
          <td><%= client.name %></td>
          <td><%= client.country %></td>
          <td><%= link_to 'Edit', edit_client_path(client) %></td>
          <td><%= link_to 'Delete', client_path(client),method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
      <% end %>
    </table>
   <%= link_to 'Add Client', new_client_path,class:"btn btn-primary btn-md" %>
  
</div>

app/views/clients/new.html.erb
<%= render 'form' %>  

app/views/employees/_form.html.erb
<div class="container">
  <h1>Add New Employee</h1>
    <div class="jumbotron">
      <%= form_with scope: :employee, url: employees_path  ,local: true do |form| %>
      <% if @employee.errors.any? %>
          <div id="error_explanation">
            <ul>
              <% @employee.errors.full_messages.each do |msg| %>
                <li style="color:gray;"><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= form.text_field :name , placeholder:'Enter Name',class:"form-control", required: true %>
        </div>
        <div class="form-group">
          <%= form.text_field :email , placeholder:'Enter email', class:"form-control", required: true %>
        </div>
         <div class="form-group">
           <%= form.text_field :experience , placeholder:'Enter Experience', class:"form-control", required: true  %>
        </div>
        <div class="form-group">
          <%= form.select(:technology_id,Technology::LIST,{include_blank: 'Select Technology'},{class:"form-control", required: 'true'})%>
        </div>
        <div class="form-group">
           <%= form.select(:role,["Developer","Project Manager"],{include_blank: 'Select Role'},{class:"form-control", required: 'true'})%>
        </div>
         <div class="form-group">
           <%= form.select(:status,{:Active=> true,:Deactive=>false},{include_blank: 'Select Status'},{class:"form-control", required: 'true'})%>
        </div>
        <%= form.submit 'Submit' ,class:"btn btn-primary btn-md"%>
        <%= link_to 'Back', employees_path, class:"btn btn-primary btn-md"%>
      <% end %>
      
    </div>
</div>

app/views/employees/edit.html.erb
<div class="container">
  <h1>Edit Employee</h1>
    <div class="jumbotron">
      <%= form_with model: @employee,local: true do |form| %>
      <% if @employee.errors.any? %>
          <div id="error_explanation">
            <ul>
              <% @employee.errors.full_messages.each do |msg| %>
                <li style="color:gray;"><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
       <div class="form-group">
          <%= form.text_field :name , placeholder:'Enter Name',class:"form-control", required: true %>
        </div>
        <div class="form-group">
          <%= form.text_field :email , placeholder:'Enter email', class:"form-control", required: true %>
        </div>
         <div class="form-group">
           <%= form.text_field :experience , placeholder:'Enter Experience', class:"form-control", required: true  %>
        </div>
        <div class="form-group">
          <%= form.select(:technology_id,Technology::LIST,{include_blank: 'Select Technology'},{class:"form-control", required: 'true'})%>
        </div>
        <div class="form-group">
           <%= form.select(:role,["Developer","Project Manager"],{include_blank: 'Select Role'},{class:"form-control", required: 'true'})%>
        </div>
         <div class="form-group">
           <%= form.select(:status,{:Active=> true,:Deactive=>false},{include_blank: 'Select Status'},{class:"form-control", required: 'true'})%>
        </div>
        <%= form.submit 'Submit' ,class:"btn btn-primary btn-md"%>
        <%= link_to 'Back', employees_path, class:"btn btn-primary btn-md"%>
      <% end %>
      
    </div>
</div>

app/views/employees/index.html.erb
<div class="container">
  <h1  style="font-family:arial">Listing All employees</h1>
  <div class="jumbotron">
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <th>E-mail</th>
        <th>Experience</th>
        <th>Technology</th>
        <th>Role</th>
        <th>Status</th>
        <th></th>
        <th></th>
      </tr>
     <% @employee.each do |employee| %>
      <tr>
          <td><%= employee.name %></td>
          <td><%= employee.email %></td>
          <td><%= employee.experience %></td>
          <td><%= employee.tech(employee.name) %></td>

          <td><%= employee.role %></td>
          <td><%= {"Active"=>true,"Deactive"=>false}.index(employee.status) %></td>
         <td><%= link_to 'Edit', edit_employee_path(employee)%></td>
          <td><%= link_to 'Delete', employee_path(employee),method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
      <% end %>
    </table>
   <%= link_to 'Add Employee', new_employee_path,class:"btn btn-primary btn-md" %>
</div>

app/views/employees/new.html.erb
<%= render 'form' %>  

app/views/layouts/_message.html.erb
<div class="row">
 	<div class="col-xs-10 col-xs-offset-1 ">
 	<% flash.each do |name,msg| %>
		<div class='alert alert-<%="#{name}"%>'>
			<a href="#" class="close" data-dismiss="alert">&#215;</a>
			<%= content_tag :div,msg,:id=>"flash_#{name}" if msg.is_a?(String) %>
		</div>
   	<% end %>
   </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-light"  style="background-color:#FFbc34; border-radius:0px;">
  <div class="container-fluid">
    <div class="navbar-header">
       <a class="navbar-brand" href="#" style= "color:black">Bacancy Technology</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Employees", employees_path, style: 'color:black' %></li>
      <li><%= link_to "Projects", projects_path, style: 'color:black' %></li>
      <li><%= link_to "Clients", clients_path ,style: 'color:black' %></li>
      <li><%= link_to "Technology", technologies_path,  style: 'color:black'%></li>
    </ul>
        <ul class="nav navbar-nav navbar-right">
      <li><%=link_to logins_path , style: 'color:black' do %>
        <i class="glyphicon glyphicon-log-in" style= "color:black"></i> Login
        <%end%>  
    </ul>
  </div>
</nav> 

app/views/layouts/_navigationadmin.html.erb
<nav class="navbar navbar-light"  style="background-color:#FFbc34; border-radius:0px;">
  <div class="container-fluid">
    <div class="navbar-header">
       <a class="navbar-brand" href="#" style= "color:black">Bacancy Technology</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Employees", employees_path, style: 'color:black' %></li>
      <li><%= link_to "Projects", projects_path, style: 'color:black' %></li>
      <li><%= link_to "Clients", clients_path ,style: 'color:black' %></li>
      <li><%= link_to "Technology", technologies_path,  style: 'color:black'%></li>
    </ul>
        <ul class="nav navbar-nav navbar-right">
        <li><%=link_to new_login_path , style: 'color:black' do %>
          <i class="glyphicon glyphicon-user" style= "color:black"></i> Add PM
        <%end%>  
         <li><%=link_to sessions_destroy_path, style: 'color:black' do %>
        <i class="glyphicon glyphicon-log-out" style="color:black"></i> Logout
        <%end%>
       </li>
    </ul>
  </div>
</nav> 

app/views/layouts/_navigationlogout.html.erb
<nav class="navbar navbar-light" style="background-color:#FFbc34; border-radius:0px;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#" style= "color:black">Bacancy Technology</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Employees", employees_path, style: 'color:black' %></li>
      <li><%= link_to "Projects", projects_path, style: 'color:black' %></li>
      <li><%= link_to "Clients", clients_path ,style: 'color:black' %></li>
      <li><%= link_to "Technology", technologies_path,  style: 'color:black'%></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
       <li><%=link_to login_path(session[:checkuser_id]),method:"delete", style: 'color:black' do %>
       	<i class="glyphicon glyphicon-log-out" style="color:black"></i> Logout
       	<%end%>
       </li>
    </ul>
  </div>
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if session[:checkuser_id]!=nil %>
      <% @type = Login.ProvideType(session[:checkuser_id])%>
      <% if @type == 'Admin'%>
        <%= render 'layouts/navigationadmin'%>
      <% else %>
        <%= render 'layouts/navigationlogout'%>
      <%end%>
    <%else %>
      <%= render 'layouts/navigation'%>
    <% end%>
      <%= render 'layouts/message'%>
      <%= yield %>
  </body>
</html>

app/views/logins/index.html.erb
<div class="container">
  <h1>Log In</h1>
  <div class="jumbotron">
    <%= form_with scope: :login, url: sessions_create_path	 ,local: true do |form| %>
			<% if @login.errors.any? %>
	      <div id="error_explanation">
	        <ul>
	          <% @login.errors.full_messages.each do |msg| %>
	            <li style="color:gray;"><%= msg %></li>
	          <% end %>
	        </ul>
	      </div>
	    <% end %>
			<div class="form-group">
        <%= form.select(:logintype,["Admin","Project Manager"],{include_blank: 'Select Login Type'},{class:"form-control", required: 'true'})%>
      </div>
			<div class="form-group">
     		<%= form.text_field :username , placeholder:'Enter Email id', class:"form-control", required:true %>
			</div>
			<div class="form-group">
      	<%= form.password_field :password , placeholder:'Enter Password', class:"form-control", required:true %>
			</div>
			<div class="form-group">
				<%= form.submit 'Login' ,class:"btn btn-primary btn-md"%>
			</div>
		<%end%>
	</div>
</div>

app/views/logins/new.html.erb
<div class="container">
  <h1>Log In</h1>
  <div class="jumbotron">
    <%= form_with scope: :login, url: logins_path	 ,local: true do |form| %>
			<% if @login.errors.any? %>
	      <div id="error_explanation">
	        <ul>
	          <% @login.errors.full_messages.each do |msg| %>
	            <li style="color:gray;"><%= msg %></li>
	          <% end %>
	        </ul>
	      </div>
	    <% end %>
			<div class="form-group">
        <%= form.select(:logintype,["Admin","Project Manager"],{include_blank: 'Select Role'},{class:"form-control", required: 'true'})%>
      </div>
			<div class="form-group">
     		<%= form.text_field :username , placeholder:'Enter Email id', class:"form-control", required:true %>
			</div>
			<div class="form-group">
      	<%= form.password_field :password , placeholder:'Enter Password', class:"form-control", required:true %>
			</div>
			<div class="form-group">
				<%= form.submit 'Register' ,class:"btn btn-primary btn-md"%>
			</div>
		<%end%>
	</div>
</div>

app/views/projects/_form.html.erb
<div class="container">
  <h1>Add New Project</h1>
    <div class="jumbotron">
      <%= form_with scope: :project, url: projects_path  ,local: true do |form| %>
        <% if @project.errors.any? %>
          <div id="error_explanation">
            <ul>
              <% @project.errors.full_messages.each do |msg| %>
                <li style="color:gray;"><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= form.text_field :name , placeholder:'Enter Name',class:"form-control", required: true %>
        </div>
        <div class="form-group">
           <%= form.date_field :start_date , class:"form-control datepicker", required: true %>
        </div>
        <div class="form-group">
           <%= form.date_field :end_date ,class:"form-control datepicker", required: true %>
        </div>
         <div class="form-group">
           <%= form.text_field :budget , placeholder:'Enter Budget', class:"form-control", required: true  %>
        </div>
        <div class="form-group">
           <%= form.select(:pm, Employee.providePM ,{include_blank: 'Select Project manager'},{class:"form-control", required: 'true'})%>
        </div>
       <div class="form-group">
           <%= form.select(:client_id,Client::LIST,{include_blank: 'Select Client'},{class:"form-control", required: 'true'})%>
        </div>
        <div class="form-group">
          <%= form.select(:technology_id,Technology::LIST,{include_blank: 'Select Technology'},{class:"form-control", required: 'true'})%>
        </div>
        <div class="form-group">
          <%= form.select :employee, Employee::LIST, {:include_hidden => false}, :multiple => true%>
        </div>
        <%= form.submit 'Submit' ,class:"btn btn-primary btn-md"%>
        <%= link_to 'Back', employees_path, class:"btn btn-primary btn-md"%>
      <% end %>
      
    </div>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <h1>Add New Project</h1>
    <div class="jumbotron">
      <%= form_with model: @project,local: true do |form| %>
        <% if @project.errors.any? %>
          <div id="error_explanation">
            <ul>
              <% @project.errors.full_messages.each do |msg| %>
                <li style="color:gray;"><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= form.text_field :name , placeholder:'Enter Name',class:"form-control",required: true %>
        </div>
        <div class="form-group">
           <%= form.date_field :start_date , class:"form-control datepicker",required: true %>
        </div>
        <div class="form-group">
           <%= form.date_field :end_date ,class:"form-control datepicker",required: true %>
        </div>
         <div class="form-group">
           <%= form.text_field :budget , placeholder:'Enter Budget', class:"form-control",required: true  %>
        </div>
        <div class="form-group">
           <%= form.select(:pm, Employee.providePM ,{include_blank: 'Select Project manager'},{ class:"form-control",required: 'true'} )%>
        </div>
       <div class="form-group">
           <%= form.select(:client_id,Client::LIST,{include_blank: 'Select Client'},{class:"form-control",required: 'true'})%>
        </div>
        <div class="form-group">
          <%= form.select(:technology_id,Technology::LIST,{include_blank: 'Select Technology'},{class:"form-control",required: 'true'})%>
        </div>
        <div class="form-group">
          <%#= form.select :employee, Employee::LIST,{include_blank: false},{ :multiple =>true, :size => 4, class:"multiselect-ui form-control", id:"multi-select-demo"}%>
          <%= form.select :employee, Employee::LIST, {:include_hidden => false}, :multiple => true,required: 'true' %>
        </div>
        <%= form.submit 'Submit' ,class:"btn btn-primary btn-md"%>
        <%= link_to 'Back', employees_path, class:"btn btn-primary btn-md"%>
      <% end %>
      
    </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <h1  style="font-family:arial">Listing All Project</h1>
  <div class="jumbotron">
    <form>
      <div class="col-sm-8" style="padding:0px 25px 0px 0px">
      <%= select_tag :qry, options_for_select(Employee.providePM),{include_blank: 'Select Project Manager', class:"form-control"}%>
    </div>
      <button type='submit' class="btn btn-primary">Filter</button>
      <%= link_to 'Show All', projects_path,class:"btn btn-primary btn-md" %>
    </form>
    <br/>
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Budget</th>
        <th>Project Manager</th>
        <th>Client</th>
        <th>Technology</th>
        <th>Employees</th>
        <th>Action</th>
        <th></th>
      </tr>
     <% @project.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.start_date %></td>
        <td><%= project.end_date %></td>
        <td><%= project.budget %></td>
        <td><%= project.projectPM(project.pm).name %></td>
        <td><%= project.client.name %></td>
        <td><%= project.technology.name %></td>
        <% l = project.projectPM(project.employee).length %>
        <td>
          <% project.projectPM(project.employee).each_with_index do |employee,index|%>
              <%if l == index+1%>
              <%= employee.name%>
              <%else%>
              <%= employee.name+',' %>
              <% end %>
            <%end%>
        </td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Delete', project_path(project) ,method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
      <% end %>
    </table>
   <%= link_to 'Add Project', new_project_path,class:"btn btn-primary btn-md" %>
</div>

app/views/projects/new.html.erb
<%= render 'form' %>  

app/views/technologies/edit.html.erb
<div class="container">
  <h1>Add New Technology</h1>
    <div class="jumbotron">
      <%= form_with scope: :technology,url: technology_path,method: :put,local: true do |form| %>
	      <% if @technology.errors.any? %>
		      <div id="error_explanation">
		        <ul>
		          <% @technology.errors.full_messages.each do |msg| %>
		            <li style="color:gray;"><%= msg %></li>
		          <% end %>
		        </ul>
		      </div>
		    <% end %>
        <div class="form-group">
          <%= form.text_field :name , placeholder:'Enter Name',class:"form-control", required: true  %>
        </div>
        <%= form.submit 'Submit' ,class:"btn btn-primary btn-md"%>
      <% end %>
    </div>
</div>

app/views/technologies/index.html.erb
<div class="container">
  <h1  style="font-family:arial">Listing All technologies</h1>
  <div class="jumbotron">
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <th></th>
        <th></th>
      </tr>
     <% @technology.each do |technology| %>
      <tr>
          <td><%= technology.name %></td>
         
          <td><%= link_to 'Edit', edit_technology_path(technology) %></td>
          <td><%= link_to 'Delete', technology_path(technology),method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
      <% end %>
    </table>
   <%= link_to 'Add technology', new_technology_path,class:"btn btn-primary btn-md" %>
  
</div>

app/views/technologies/new.html.erb
<div class="container">
  <h1>Add New Technology</h1>
    <div class="jumbotron">
      <%= form_with scope: :technology, url: technologies_path  ,local: true do |form| %>
        <% if @technology.errors.any? %>
          <div id="error_explanation">
            <ul>
              <% @technology.errors.full_messages.each do |msg| %>
                <li style="color:gray;"><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= form.text_field :name , placeholder:'Enter Name',class:"form-control", required: true  %>
        </div>
        <%= form.submit 'Submit' ,class:"btn btn-primary btn-md"%>
       <%= link_to 'Back', technologies_path, class:"btn btn-primary btn-md"%>
      <% end %>
    </div>
</div>